### ISSUE TITLE
translate korean to english

### ISSUE THREAD

**Issue by whwnsdlr1** [whwnsdlr1/tensorflow.js-classification-example#1]
페이지 내 한글 텍스트의 영어번역이 필요 합니다.

frontend/src/components/Main.vue - 123번 line
def: ...{ html: }
html value에 포함된 한글의 영어로 변환이 필요하며 자연스럽게 문장을 바꾸거나 추가 해석을 달아주시는 것 또한 환영합니다.

관심 감사합니다. !

**Comment by kye199** [comment]
영어번역을 왼료하였는데 어떤 방식으로 드리는 것이 좋을까요?

**Comment by kye199** [comment]
혹시 번역할 수 있는 po파일이 있나요?

**Comment by whwnsdlr1** [comment]
소스 코드 내에 한글 텍스트가 포함되어 있어요.
frontend/src/components/Main.vue
내에 있는 텍스트를 교체 하신 후에

https://wayhome25.github.io/git/2017/07/08/git-first-pull-request-story/
위의 글을 참고 하셔서 Pull Request 해주시면 되요.

**Comment by HwaGyeong** [comment]
branch를 생성하고 compare &pull request를 했는데 there isn't  anything to compare와 같은 문구가 뜨고, create  pull request가 뜨지 않습니다 방법을 알고계신가요?

**Comment by whwnsdlr1** [comment]
파일의 위치가 지켜져야 합니다.
master 위치: /frontend/src/components/Main.vue
branch 위치: /Main.vue

master 위치와 맞춰주시고
로컬 git에서 commit 시 Main.vue가 add가 아닌 modify로 체크되는지 확인해 주세요.
로컬에서 commit 후 pull 하시고 branch github 홈페이지에서 PR해 주시면 됩니다.

**Comment by whwnsdlr1** [comment]
수고하셨습니다!
데모 페이지 반영은 빌드 후에 적용됩니다. 오늘이나 내일 빌드하여 올리겠습니다.

**Comment by kye199** [comment]
감사합니다
